version: '3.8'
services:
  api:
    restart: always
    build: .
    expose:
      - ${PORT}
    volumes:
    - .:/usr/src/app
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on: 
      - api

volumes: 
  data: {}